version: 0.2

phases:

  install:
    commands:
      - codebuild-breakpoint
      - yum install -y amazon-cloudwatch-agent
      - amazon-cloudwatch-agent-ctl -a status
      - wget https://github.com/grafana/k6/releases/download/v0.35.0/k6-v0.35.0-linux-amd64.rpm -O ~/k6.rpm
      - rpm -i ~/k6.rpm
      - cp ./statsd.json /opt/aws/amazon-cloudwatch-agent/etc/statsd.json

  build:
    commands:
      - echo $(pwd)
      - K6_STATSD_ENABLE_TAGS=true k6 run --out statsd --summary-time-unit=s k6.js

  post_build:
    commands:
      - echo "Build complete, waiting for stats to sync"
      - sleep 10
